### ISSUE TITLE
Drop Timestamp Label

### ISSUE THREAD

**Issue by shaardie** [NVIDIA/gpu-feature-discovery#8]
Having a label changing that often as a timestamp can lead to serous trouble.
For example, if using a Watch in Kubernetes, you will get alerted on every timestamp change despite the fact that nothing happens on the node.
Another issue  is monitoring. Most time series based monitoring like Prometheus have increased complexity with every unique time series and having labels as metadata lead to a new series for every timestamp.

Honestly, I do not see any usefulness in having a timestamp as a label. Maybe you can help me understand. Otherwise, I would be glad to help removing the timestamp.

**Comment by elezar** [comment]
The timestamp is used to test for "liveness", especially in our debug and testing scenarios. With this said, it isn't strictly necessary and could be made optional -- or another mechanism used to check this.
